// Generated by scripts/update-canada.ts on 2026-09-16. Do not edit by hand.
//
// Sources: Environment and Climate Change Canada, National Inventory Report,
// Annex 7: Electricity in Canada: Summary and Intensity Tables
// (https://data-donnees.az.ec.gc.ca/data/substances/monitor/canada-s-official-greenhouse-gas-inventory/),
// provincial generation by fuel. Contains information licensed under the Open
// Government Licence - Canada (https://open.canada.ca/en/open-government-licence-canada).
// Ember Yearly Electricity Data (https://ember-energy.org/data/yearly-electricity-data/,
// CC BY 4.0) supplies Canadian lifecycle emissions factors for 2023.
// Changes: intensity = sum(generation by fuel x Ember Canada factor) / generation,
// rounded to 0.1 gCO2e/kWh. Check: the same method on the national table gives
// 153.0 against Ember's 174.431 (-12.3%). The gap comes from
// scope: Annex 7 covers main-activity producers only, while Ember also counts
// industrial autoproducers.

export const CA_NIR_SOURCE = {
  name: "Environment and Climate Change Canada, National Inventory Report Annex 7, lifecycle-adjusted with Ember factors",
  url: "https://data-donnees.az.ec.gc.ca/data/substances/monitor/canada-s-official-greenhouse-gas-inventory/",
  license: "Open Government Licence - Canada (NIR); CC BY 4.0 (Ember factors)",
  retrieved: "2026-09-16",
} as const;

/** Annual lifecycle emissions intensity of generation, gCO2e/kWh, by Electricity Maps zone key. */
export const CA_NIR_ZONES: Readonly<Record<string, { intensity: number; year: number }>> = {
  "CA-AB": { intensity: 575.1, year: 2023 },
  "CA-ON": { intensity: 104.2, year: 2023 },
  "CA-QC": { intensity: 27.7, year: 2023 },
};
