/**
 * Grid-level annual averages for countries whose national average hides very
 * different grids. Each file in this folder is generated by a script under
 * scripts/; this index only merges them.
 */
import { CA_NIR_ZONES } from "./ca-nir.js";
import { US_EGRID_ZONES } from "./us-egrid.js";

export type ZoneBaselineSource = "epa-egrid-annual" | "eccc-nir-annual";

export interface ZoneBaseline {
  /** Annual lifecycle emissions intensity of generation, gCO2e/kWh. */
  intensity: number;
  year: number;
  source: ZoneBaselineSource;
}

function tag(zones: Readonly<Record<string, { intensity: number; year: number }>>, source: ZoneBaselineSource) {
  return Object.fromEntries(Object.entries(zones).map(([zone, value]) => [zone, { ...value, source }]));
}

/** Annual averages by Electricity Maps zone key. */
export const ZONE_BASELINE_INTENSITY: Readonly<Record<string, ZoneBaseline>> = {
  ...tag(US_EGRID_ZONES, "epa-egrid-annual"),
  ...tag(CA_NIR_ZONES, "eccc-nir-annual"),
};
