/**
 * Regenerates src/data/zone-baseline/us-egrid.ts with annual carbon intensity
 * for US grid zones, from EPA eGRID balancing authority data.
 *
 *   npm run update:egrid
 *   npm run update:egrid -- --egrid egrid2023_data_rev2.xlsx --ember release_generation_yearly_global.csv
 *
 * eGRID reports direct combustion emissions. To stay comparable with the
 * Ember country averages, this script uses each balancing authority's
 * generation mix and applies Ember's US lifecycle factors for the same year.
 * It checks the method against Ember's US national figure and fails if they
 * differ by more than 5%.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";
import { REGIONS } from "../src/data/regions.js";
import { loadEmberRows } from "./lib/ember.js";
import { checkNational, emberCountryYear, mixIntensity } from "./lib/lifecycle.js";
import { readSheet, sheetNames } from "./lib/xlsx.js";

// Latest official release. EPA paused eGRID after this edition.
const EGRID_URL = "https://www.epa.gov/system/files/documents/2025-06/egrid2023_data_rev2.xlsx";
const EGRID_EDITION = "eGRID2023 (Revision 2)";
const OUTPUT = fileURLToPath(new URL("../src/data/zone-baseline/us-egrid.ts", import.meta.url));

// eGRID annual net generation columns (suffix after BAGEN / USGEN) -> Ember source.
const FUEL_COLUMNS: Record<string, string> = {
  ACL: "Coal",
  AGS: "Gas",
  AOL: "Other fossil",
  AOF: "Other fossil",
  AOP: "Other fossil",
  ANC: "Nuclear",
  AHY: "Hydro",
  ABM: "Bioenergy",
  AWI: "Wind",
  ASO: "Solar",
  AGT: "Other renewables",
};

const { values } = parseArgs({ options: { egrid: { type: "string" }, ember: { type: "string" } } });

async function egridPath(): Promise<string> {
  if (values.egrid) return values.egrid;
  const { mkdtempSync } = await import("node:fs");
  const { tmpdir } = await import("node:os");
  const { join } = await import("node:path");
  console.error(`Downloading ${EGRID_URL}`);
  const res = await fetch(EGRID_URL);
  if (!res.ok) throw new Error(`eGRID download failed: ${res.status} ${res.statusText}`);
  const path = join(mkdtempSync(join(tmpdir(), "egrid-")), "egrid.xlsx");
  writeFileSync(path, Buffer.from(await res.arrayBuffer()));
  return path;
}

/** Rows keyed by eGRID's short column codes, which sit on the second header row. */
function keyedRows(path: string, prefix: "BA" | "US"): Record<string, string>[] {
  const name = sheetNames(path).find((s) => new RegExp(`^${prefix}\\d{2}$`).test(s));
  if (!name) throw new Error(`No ${prefix} sheet in ${path}`);
  const [, codes, ...rows] = readSheet(path, name);
  return rows.map((r) => Object.fromEntries(codes!.map((c, i) => [c, r[i] ?? ""])));
}

function lifecycleIntensity(row: Record<string, string>, prefix: "BAGEN" | "USGEN", factors: Map<string, number>): number {
  return mixIntensity(
    Object.entries(FUEL_COLUMNS).map(([suffix, source]) => {
      const factor = factors.get(source);
      if (factor === undefined) throw new Error(`No Ember US factor for ${source}`);
      return { generation: Number(row[prefix + suffix] || 0), factor };
    }),
  );
}

const path = await egridPath();
const baRows = keyedRows(path, "BA");
const usRow = keyedRows(path, "US")[0]!;
const year = Number(usRow.YEAR);

const ember = emberCountryYear(await loadEmberRows(values.ember), "USA", year);
const { factors } = ember;
const emberNational = ember.intensity;
const egridNational = lifecycleIntensity(usRow, "USGEN", factors);
const deviation = checkNational(`US ${year} (eGRID)`, egridNational, emberNational);

const zones = [...new Set(REGIONS.filter((r) => r.country === "US").map((r) => r.gridZone))].sort();
const entries = zones.map((zone) => {
  // Electricity Maps US zone keys end with the EIA balancing authority code.
  const code = zone.split("-").at(-1)!;
  const row = baRows.find((r) => r.BACODE === code);
  if (!row) throw new Error(`eGRID has no balancing authority ${code} for zone ${zone}`);
  const intensity = Math.round(lifecycleIntensity(row, "BAGEN", factors) * 10) / 10;
  return `  "${zone}": { intensity: ${intensity}, year: ${year} },`;
});

const today = new Date().toISOString().slice(0, 10);
writeFileSync(
  OUTPUT,
  `// Generated by scripts/update-egrid.ts on ${today}. Do not edit by hand.
//
// Sources: US EPA ${EGRID_EDITION} balancing authority net generation by fuel
// (https://www.epa.gov/egrid, public domain), and Ember Yearly Electricity Data
// (https://ember-energy.org/data/yearly-electricity-data/, CC BY 4.0) for US
// lifecycle emissions factors in ${year}.
// Changes: intensity = sum(generation by fuel x Ember US factor) / generation,
// rounded to 0.1 gCO2e/kWh. Check: the same method on eGRID's US total gives
// ${egridNational.toFixed(1)} against Ember's ${emberNational} (${deviation >= 0 ? "+" : ""}${(deviation * 100).toFixed(1)}%).

export const US_EGRID_SOURCE = {
  name: "US EPA ${EGRID_EDITION}, lifecycle-adjusted with Ember factors",
  url: "https://www.epa.gov/egrid",
  license: "Public domain (eGRID); CC BY 4.0 (Ember factors)",
  retrieved: "${today}",
} as const;

/** Annual lifecycle emissions intensity of generation, gCO2e/kWh, by Electricity Maps zone key. */
export const US_EGRID_ZONES: Readonly<Record<string, { intensity: number; year: number }>> = {
${entries.join("\n")}
};
`,
);
console.error(`Wrote ${entries.length} zones to ${OUTPUT}`);
