/**
 * Regenerates src/data/baseline-intensity.ts from Ember's Yearly Electricity
 * Data (CC BY 4.0). Run once a year after Ember publishes a new release:
 *
 *   npm run update:baseline
 *   npm run update:baseline -- path/to/release_generation_yearly_global.csv
 *
 * For each country that has a cloud region, it keeps the latest year's
 * "Total generation" emissions intensity.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { REGIONS } from "../src/data/regions.js";
import { loadEmberRows } from "./lib/ember.js";

const OUTPUT = fileURLToPath(new URL("../src/data/baseline-intensity.ts", import.meta.url));

// ISO 3166-1 alpha-2 -> alpha-3. Ember keys countries by alpha-3.
const ALPHA3: Record<string, string> = {
  AE: "ARE", AT: "AUT", AU: "AUS", BE: "BEL", BH: "BHR", BR: "BRA", CA: "CAN", CH: "CHE",
  CL: "CHL", DE: "DEU", DK: "DNK", ES: "ESP", FI: "FIN", FR: "FRA", GB: "GBR", HK: "HKG",
  ID: "IDN", IE: "IRL", IL: "ISR", IN: "IND", IT: "ITA", JP: "JPN", KR: "KOR", MX: "MEX",
  MY: "MYS", NL: "NLD", NO: "NOR", NZ: "NZL", PL: "POL", QA: "QAT", SA: "SAU", SE: "SWE",
  SG: "SGP", TH: "THA", TW: "TWN", US: "USA", ZA: "ZAF",
};

const countries = [...new Set(REGIONS.map((r) => r.country))].sort();
const missingCodes = countries.filter((c) => !ALPHA3[c]);
if (missingCodes.length) {
  throw new Error(`Add alpha-3 codes for: ${missingCodes.join(", ")}`);
}

const latest = new Map<string, { intensity: number; year: number }>();
for (const row of await loadEmberRows(process.argv[2])) {
  const value = row["Emissions intensity (gCO2e/kWh)"];
  if (row["Electricity source"] !== "Total generation" || row["Area type"] !== "Country or economy" || !value) continue;
  const year = Number(row.Year);
  const intensity = Number(value);
  const prev = latest.get(row["ISO 3 code"]!);
  if (Number.isFinite(intensity) && (!prev || year > prev.year)) latest.set(row["ISO 3 code"]!, { intensity, year });
}

const entries = countries.map((c) => {
  const value = latest.get(ALPHA3[c]!);
  if (!value) throw new Error(`Ember has no intensity data for ${c} (${ALPHA3[c]})`);
  return `  ${c}: { intensity: ${Math.round(value.intensity * 10) / 10}, year: ${value.year} },`;
});

const today = new Date().toISOString().slice(0, 10);
writeFileSync(
  OUTPUT,
  `// Generated by scripts/update-baseline.ts on ${today}. Do not edit by hand.
//
// Source: Ember, Yearly Electricity Data (https://ember-energy.org/data/yearly-electricity-data/),
// licensed under CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/).
// Changes: kept the latest year of "Total generation" emissions intensity for
// each country with a cloud region, rounded to 0.1 gCO2e/kWh.

export const BASELINE_SOURCE = {
  name: "Ember Yearly Electricity Data",
  url: "https://ember-energy.org/data/yearly-electricity-data/",
  license: "CC BY 4.0",
  retrieved: "${today}",
} as const;

/** Annual lifecycle emissions intensity of electricity generation, gCO2e/kWh, by ISO alpha-2 country. */
export const BASELINE_INTENSITY: Readonly<Record<string, { intensity: number; year: number }>> = {
${entries.join("\n")}
};
`,
);
console.error(`Wrote ${entries.length} countries to ${OUTPUT}`);
