// Generated by scripts/update-baseline.ts on 2026-09-16. Do not edit by hand.
//
// Source: Ember, Yearly Electricity Data (https://ember-energy.org/data/yearly-electricity-data/),
// licensed under CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/).
// Changes: kept the latest year of "Total generation" emissions intensity for
// each country with a cloud region, rounded to 0.1 gCO2e/kWh.

export const BASELINE_SOURCE = {
  name: "Ember Yearly Electricity Data",
  url: "https://ember-energy.org/data/yearly-electricity-data/",
  license: "CC BY 4.0",
  retrieved: "2026-09-16",
} as const;

/** Annual lifecycle emissions intensity of electricity generation, gCO2e/kWh, by ISO alpha-2 country. */
export const BASELINE_INTENSITY: Readonly<Record<string, { intensity: number; year: number }>> = {
  AE: { intensity: 467.5, year: 2024 },
  AT: { intensity: 116.7, year: 2025 },
  AU: { intensity: 524.6, year: 2025 },
  BE: { intensity: 125.9, year: 2025 },
  BH: { intensity: 902.5, year: 2024 },
  BR: { intensity: 109.9, year: 2025 },
  CA: { intensity: 190.7, year: 2025 },
  CH: { intensity: 39.1, year: 2025 },
  CL: { intensity: 290.6, year: 2025 },
  DE: { intensity: 334.1, year: 2025 },
  DK: { intensity: 99.9, year: 2025 },
  ES: { intensity: 153.5, year: 2025 },
  FI: { intensity: 57.2, year: 2025 },
  FR: { intensity: 41.4, year: 2025 },
  GB: { intensity: 222.2, year: 2025 },
  HK: { intensity: 675.6, year: 2024 },
  ID: { intensity: 681.1, year: 2024 },
  IE: { intensity: 263.3, year: 2025 },
  IL: { intensity: 492.9, year: 2025 },
  IN: { intensity: 671.4, year: 2025 },
  IT: { intensity: 284.2, year: 2025 },
  JP: { intensity: 477.4, year: 2025 },
  KR: { intensity: 417.1, year: 2025 },
  MX: { intensity: 474, year: 2025 },
  MY: { intensity: 605.5, year: 2025 },
  NL: { intensity: 253.7, year: 2025 },
  NO: { intensity: 28.1, year: 2025 },
  NZ: { intensity: 92.7, year: 2025 },
  PL: { intensity: 590.9, year: 2025 },
  QA: { intensity: 581.9, year: 2025 },
  SA: { intensity: 691.9, year: 2024 },
  SE: { intensity: 35.3, year: 2025 },
  SG: { intensity: 497, year: 2025 },
  TH: { intensity: 525.9, year: 2025 },
  TW: { intensity: 633.6, year: 2025 },
  US: { intensity: 384.4, year: 2025 },
  ZA: { intensity: 699, year: 2025 },
};
