// Generated by scripts/update-egrid.ts on 2026-09-16. Do not edit by hand.
//
// Sources: US EPA eGRID2023 (Revision 2) balancing authority net generation by fuel
// (https://www.epa.gov/egrid, public domain), and Ember Yearly Electricity Data
// (https://ember-energy.org/data/yearly-electricity-data/, CC BY 4.0) for US
// lifecycle emissions factors in 2023.
// Changes: intensity = sum(generation by fuel x Ember US factor) / generation,
// rounded to 0.1 gCO2e/kWh. Check: the same method on eGRID's US total gives
// 400.2 against Ember's 392.9 (+1.9%).

export const ZONE_BASELINE_SOURCE = {
  name: "US EPA eGRID2023 (Revision 2), lifecycle-adjusted with Ember factors",
  url: "https://www.epa.gov/egrid",
  license: "Public domain (eGRID); CC BY 4.0 (Ember factors)",
  retrieved: "2026-09-16",
} as const;

/** Annual lifecycle emissions intensity of generation, gCO2e/kWh, by Electricity Maps zone key. */
export const ZONE_BASELINE_INTENSITY: Readonly<Record<string, { intensity: number; year: number }>> = {
  "US-CAL-CISO": { intensity: 248.8, year: 2023 },
  "US-CAL-LDWP": { intensity: 539.6, year: 2023 },
  "US-CAR-SC": { intensity: 749, year: 2023 },
  "US-MIDA-PJM": { intensity: 385.8, year: 2023 },
  "US-MIDW-MISO": { intensity: 494.4, year: 2023 },
  "US-NW-BPAT": { intensity: 129.2, year: 2023 },
  "US-NW-GCPD": { intensity: 24, year: 2023 },
  "US-NW-NEVP": { intensity: 408.2, year: 2023 },
  "US-NW-PACE": { intensity: 600.2, year: 2023 },
  "US-NW-WACM": { intensity: 746.6, year: 2023 },
  "US-SW-AZPS": { intensity: 690.9, year: 2023 },
  "US-TEX-ERCO": { intensity: 395.2, year: 2023 },
};
